# Assignment7

そのまま課題ファイルで編集しないでください。課題ファイルを複製してから課題を回答してください。

Do not edit the original assignment file directly. Make a copy of the assignment file first, then complete your answers in the copied file.

## 課題1

pandasでDataフォルダの```example.json```を読み込む。

Task 1. Use pandas to read example.json from the Data folder.

In [ ]:
import os #os is Python's built in Operating System module and it provides functions for working with files, folders, file paths, and the existing working directory.

print(os.getcwd())

/Users/dolgorsurengombojavgmail.com/Desktop/chss_2026_assignment

In [7]:
import os

print(os.listdir())

['state-areas.csv', '.DS_Store', 'example.json', 'assignment7_Dolgor.ipynb', 'state-abbrevs.csv', 'grouped.csv', 'README.md', '.git', 'state-population.csv']

In [ ]:
with open("example.json", "r", encoding="utf-8") as file: #encoding specifies the character encoding used to interpret the text.
                              # UTF-8 is the standard encoding and supports most international characters.
                              #as the file is opened in read mode ("r"), the code reads the contents of the file and prints it to the console.
    print(file.read())

{"Name":"Honda", "Price": 10000, "Model":2005, "Power": 1300}
{"Name":"Toyota", "Price": 12000, "Model":2010, "Power": 1600}
{"Name":"Audi", "Price": 25000, "Model":2017, "Power": 1800}
{"Name":"Ford", "Price": 28000, "Model":2009, "Power": 1200}

In [ ]:
import pandas as pd

example = pd.read_json("example.json", lines=True) #lines=True is used to read the JSON file line by line. Withoug it, pandas expects the entire file to be one valid JSON object or array, and I receive an error message.
#this function is converting the JSON data into a pandas DataFrame, which is a tabular data structure that allows for easy manipulation and analysis of the data.
example

     Name  Price  Model  Power
0   Honda  10000   2005   1300
1  Toyota  12000   2010   1600
2    Audi  25000   2017   1800
3    Ford  28000   2009   1200

## 課題2

pandasでDataフォルダの```state-abbrevs.csv```、```state-areas.csv```、```state-population.csv```を読み込む。

これらのデータを使って、**2010年**アメリカの各州の人口密度を計算しよう。

Task 2. Use pandas to read the following files from the Data folder: 
state-abbrevs.csv
state-areas.csv
state-population.csv
Using these datasets, calculate the population density of each U.S. state in 2010.

In [17]:
import pandas as pd
abbrevs = pd.read_csv("state-abbrevs.csv")
areas = pd.read_csv("state-areas.csv")
population = pd.read_csv("state-population.csv")

In [ ]:
population = pd.merge(
    population,
    abbrevs,
    left_on="state/region", #The left_on parameter specifies the column in the left DataFrame (population),
    right_on="abbreviation", #specifies the column in the right DataFrame (abbrevs) to join on.
    how="left" #joins the two DataFrames based on the specified columns, keeping all rows from the left DataFrame (population) and adding matching rows from the right DataFrame (abbrevs).
)

In [27]:
population.head()

  state/region     ages  year  population    state abbreviation
0           AL  under18  2012   1117489.0  Alabama           AL
1           AL    total  2012   4817528.0  Alabama           AL
2           AL  under18  2010   1130966.0  Alabama           AL
3           AL    total  2010   4785570.0  Alabama           AL
4           AL  under18  2011   1125763.0  Alabama           AL

In [ ]:
population_2010 = population[
    (population["year"] == 2010) &
    (population["ages"] == "total") 
] ## Use Boolean indexing to filter the DataFrame. And only rows satisfying both conditions are returned.

In [31]:
population_2010.head()

,state/region,ages,year,population,state,abbreviation,area (sq. mi)
3,AL,total,2010,4785570.0,Alabama,AL,52423.0
91,AK,total,2010,713868.0,Alaska,AK,656425.0
101,AZ,total,2010,6408790.0,Arizona,AZ,114006.0
189,AR,total,2010,2922280.0,Arkansas,AR,53182.0
197,CA,total,2010,37333601.0,California,CA,163707.0

In [41]:
population_2010["density"] = (
    population_2010["population"] /
    population_2010["area (sq. mi)"]
)
density = population_2010[["state", "density"]] #selecting only the "state" and "density" columns from the population_2010 DataFrame and storing them in a new DataFrame called density
print (density)

                     state      density
3                  Alabama    91.287603
91                  Alaska     1.087509
101                Arizona    56.214497
189               Arkansas    54.948667
197             California   228.051342
283               Colorado    48.493718
293            Connecticut   645.600649
379               Delaware   460.445752
389   District of Columbia  8898.897059
475                Florida   286.597129
485                Georgia   163.409902
570                 Hawaii   124.746707
581                  Idaho    18.794338
666               Illinois   221.687472
677                Indiana   178.197831
762                   Iowa    54.202751
773                 Kansas    34.745266
858               Kentucky   107.586994
869              Louisiana    87.676099
954                  Maine    37.509990
965               Maryland   466.445797
1050         Massachusetts   621.815538
1061              Michigan   102.015794
1146             Minnesota    61.078373
1157           Mississippi    61.321530
1242              Missouri    86.015622
1253               Montana     6.736171
1338              Nebraska    23.654153
1349                Nevada    24.448796
1434         New Hampshire   140.799273
1445            New Jersey  1009.253268
1530            New Mexico    16.982737
1541              New York   356.094135
1626        North Carolina   177.617157
1637          North Dakota     9.537565
1722                  Ohio   257.549634
1733              Oklahoma    53.778278
1818                Oregon    39.001565
1829          Pennsylvania   275.966651
1914          Rhode Island   681.339159
1925        South Carolina   144.854594
2010          South Dakota    10.583512
2021             Tennessee   150.825298
2106                 Texas    93.987655
2117                  Utah    32.677188
2202               Vermont    65.085075
2213              Virginia   187.622273
2298            Washington    94.557817
2309         West Virginia    76.519582
2394             Wisconsin    86.851900
2405               Wyoming     5.768079
2490                   NaN          NaN
2539                   NaN          NaN

## 課題3

```state/region```、```ages```と```years```でデータフレームをグループして、各グループで$\frac{population}{area (sq. mi)}$の形で人口密度を計算してください。

Task 3. Group the dataframe by:
state/region
ages
year
Then calculate population density for each group in the requested format.

In [42]:
grouped_population = population.groupby(
    ["state/region", "ages", "year"]
)["population"].sum()

In [43]:
print(grouped_population)

state/region  ages     year
AK            total    1990    553290.0
                       1991    570193.0
                       1992    588736.0
                       1993    599434.0
                       1994    603308.0
                                 ...
WY            under18  2009    134960.0
                       2010    135351.0
                       2011    135407.0
                       2012    136526.0
                       2013    137679.0
Name: population, Length: 2544, dtype: float64

In [ ]:
grouped_population = grouped_population.reset_index() #converting the grouped_population Series back into a DataFrame, with the groupby keys as columns and the aggregated values as a separate column. 
print(grouped_population.head())

  state/region   ages  year  population
0           AK  total  1990    553290.0
1           AK  total  1991    570193.0
2           AK  total  1992    588736.0
3           AK  total  1993    599434.0
4           AK  total  1994    603308.0

In [ ]:
grouped_population = pd.merge(
    grouped_population,
    abbrevs,
    left_on="state/region",
    right_on="abbreviation",
    how="left"
) #adding the state names to the grouped population DataFrame by merging it with the abbrevs DataFrame.

In [46]:
print(grouped_population.head())

  state/region   ages  year  population   state abbreviation
0           AK  total  1990    553290.0  Alaska           AK
1           AK  total  1991    570193.0  Alaska           AK
2           AK  total  1992    588736.0  Alaska           AK
3           AK  total  1993    599434.0  Alaska           AK
4           AK  total  1994    603308.0  Alaska           AK

In [ ]:
grouped_population = pd.merge(
    grouped_population,
    areas,
    on="state",
    how="left"
) #adding the area information to the grouped population DataFrame.

In [48]:
print(grouped_population.head())

  state/region   ages  year  population   state abbreviation  area (sq. mi)
0           AK  total  1990    553290.0  Alaska           AK       656425.0
1           AK  total  1991    570193.0  Alaska           AK       656425.0
2           AK  total  1992    588736.0  Alaska           AK       656425.0
3           AK  total  1993    599434.0  Alaska           AK       656425.0
4           AK  total  1994    603308.0  Alaska           AK       656425.0

In [49]:
grouped_population["density"] = (
    grouped_population["population"] /
    grouped_population["area (sq. mi)"]
)

In [50]:
density = grouped_population[
    ["state/region", "ages", "year", "density"]
]

print(density)

     state/region     ages  year   density
0              AK    total  1990  0.842884
1              AK    total  1991  0.868634
2              AK    total  1992  0.896882
3              AK    total  1993  0.913180
4              AK    total  1994  0.919081
...           ...      ...   ...       ...
2539           WY  under18  2009  1.379705
2540           WY  under18  2010  1.383702
2541           WY  under18  2011  1.384275
2542           WY  under18  2012  1.395714
2543           WY  under18  2013  1.407502

[2544 rows x 4 columns]