# Assignment7

そのまま課題ファイルで編集しないでください。課題ファイルを複製してから課題を回答してください。

## 課題1

pandasでDataフォルダの```example.json```を読み込む。

In [2]:
import pandas as pd
from pathlib import Path

data_path = Path("Data/example.json")
df = pd.read_json(data_path, lines=True)
df

     Name  Price  Model  Power
0   Honda  10000   2005   1300
1  Toyota  12000   2010   1600
2    Audi  25000   2017   1800
3    Ford  28000   2009   1200

## 課題2

pandasでDataフォルダの```state-abbrevs.csv```、```state-areas.csv```、```state-population.csv```を読み込む。

これらのデータを使って、**2010年**アメリカの各州の人口密度を計算しよう。

In [3]:
state_abbrevs_path = Path("Data/state-abbrevs.csv")
df_abbrevs = pd.read_csv(state_abbrevs_path)
df_abbrevs

                   state abbreviation
0                Alabama           AL
1                 Alaska           AK
2                Arizona           AZ
3               Arkansas           AR
4             California           CA
5               Colorado           CO
6            Connecticut           CT
7               Delaware           DE
8   District of Columbia           DC
9                Florida           FL
10               Georgia           GA
11                Hawaii           HI
12                 Idaho           ID
13              Illinois           IL
14               Indiana           IN
15                  Iowa           IA
16                Kansas           KS
17              Kentucky           KY
18             Louisiana           LA
19                 Maine           ME
20               Montana           MT
21              Nebraska           NE
22                Nevada           NV
23         New Hampshire           NH
24            New Jersey           NJ
25            New Mexico           NM
26              New York           NY
27        North Carolina           NC
28          North Dakota           ND
29                  Ohio           OH
30              Oklahoma           OK
31                Oregon           OR
32              Maryland           MD
33         Massachusetts           MA
34              Michigan           MI
35             Minnesota           MN
36           Mississippi           MS
37              Missouri           MO
38          Pennsylvania           PA
39          Rhode Island           RI
40        South Carolina           SC
41          South Dakota           SD
42             Tennessee           TN
43                 Texas           TX
44                  Utah           UT
45               Vermont           VT
46              Virginia           VA
47            Washington           WA
48         West Virginia           WV
49             Wisconsin           WI
50               Wyoming           WY

In [4]:
state_areas_path = Path("Data/state-areas.csv")
df_areas = pd.read_csv(state_areas_path)
df_areas

                   state  area (sq. mi)
0                Alabama          52423
1                 Alaska         656425
2                Arizona         114006
3               Arkansas          53182
4             California         163707
5               Colorado         104100
6            Connecticut           5544
7               Delaware           1954
8                Florida          65758
9                Georgia          59441
10                Hawaii          10932
11                 Idaho          83574
12              Illinois          57918
13               Indiana          36420
14                  Iowa          56276
15                Kansas          82282
16              Kentucky          40411
17             Louisiana          51843
18                 Maine          35387
19              Maryland          12407
20         Massachusetts          10555
21              Michigan          96810
22             Minnesota          86943
23           Mississippi          48434
24              Missouri          69709
25               Montana         147046
26              Nebraska          77358
27                Nevada         110567
28         New Hampshire           9351
29            New Jersey           8722
30            New Mexico         121593
31              New York          54475
32        North Carolina          53821
33          North Dakota          70704
34                  Ohio          44828
35              Oklahoma          69903
36                Oregon          98386
37          Pennsylvania          46058
38          Rhode Island           1545
39        South Carolina          32007
40          South Dakota          77121
41             Tennessee          42146
42                 Texas         268601
43                  Utah          84904
44               Vermont           9615
45              Virginia          42769
46            Washington          71303
47         West Virginia          24231
48             Wisconsin          65503
49               Wyoming          97818
50  District of Columbia             68
51           Puerto Rico           3515

In [5]:
state_population_path = Path("Data/state-population.csv")
df_pop = pd.read_csv(state_population_path)
df_pop

     state/region     ages  year   population
0              AL  under18  2012    1117489.0
1              AL    total  2012    4817528.0
2              AL  under18  2010    1130966.0
3              AL    total  2010    4785570.0
4              AL  under18  2011    1125763.0
...           ...      ...   ...          ...
2539          USA    total  2010  309326295.0
2540          USA  under18  2011   73902222.0
2541          USA    total  2011  311582564.0
2542          USA  under18  2012   73708179.0
2543          USA    total  2012  313873685.0

[2544 rows x 4 columns]

In [6]:
#各州の名前を略称にする
df_pop2 = pd.merge(df_pop, df_abbrevs,
                left_on="state/region", right_on="abbreviation", how="left")
df_pop2

     state/region     ages  year   population    state abbreviation
0              AL  under18  2012    1117489.0  Alabama           AL
1              AL    total  2012    4817528.0  Alabama           AL
2              AL  under18  2010    1130966.0  Alabama           AL
3              AL    total  2010    4785570.0  Alabama           AL
4              AL  under18  2011    1125763.0  Alabama           AL
...           ...      ...   ...          ...      ...          ...
2539          USA    total  2010  309326295.0      NaN          NaN
2540          USA  under18  2011   73902222.0      NaN          NaN
2541          USA    total  2011  311582564.0      NaN          NaN
2542          USA  under18  2012   73708179.0      NaN          NaN
2543          USA    total  2012  313873685.0      NaN          NaN

[2544 rows x 6 columns]

In [8]:
#各州の2010年のtotalの人口のデータを作る
df_2010_total = df_pop2[(df_pop2["year"]==2010) & (df_pop2["ages"]=="total")]
df_2010_total

     state/region   ages  year   population                 state abbreviation
3              AL  total  2010    4785570.0               Alabama           AL
91             AK  total  2010     713868.0                Alaska           AK
101            AZ  total  2010    6408790.0               Arizona           AZ
189            AR  total  2010    2922280.0              Arkansas           AR
197            CA  total  2010   37333601.0            California           CA
283            CO  total  2010    5048196.0              Colorado           CO
293            CT  total  2010    3579210.0           Connecticut           CT
379            DE  total  2010     899711.0              Delaware           DE
389            DC  total  2010     605125.0  District of Columbia           DC
475            FL  total  2010   18846054.0               Florida           FL
485            GA  total  2010    9713248.0               Georgia           GA
570            HI  total  2010    1363731.0                Hawaii           HI
581            ID  total  2010    1570718.0                 Idaho           ID
666            IL  total  2010   12839695.0              Illinois           IL
677            IN  total  2010    6489965.0               Indiana           IN
762            IA  total  2010    3050314.0                  Iowa           IA
773            KS  total  2010    2858910.0                Kansas           KS
858            KY  total  2010    4347698.0              Kentucky           KY
869            LA  total  2010    4545392.0             Louisiana           LA
954            ME  total  2010    1327366.0                 Maine           ME
965            MD  total  2010    5787193.0              Maryland           MD
1050           MA  total  2010    6563263.0         Massachusetts           MA
1061           MI  total  2010    9876149.0              Michigan           MI
1146           MN  total  2010    5310337.0             Minnesota           MN
1157           MS  total  2010    2970047.0           Mississippi           MS
1242           MO  total  2010    5996063.0              Missouri           MO
1253           MT  total  2010     990527.0               Montana           MT
1338           NE  total  2010    1829838.0              Nebraska           NE
1349           NV  total  2010    2703230.0                Nevada           NV
1434           NH  total  2010    1316614.0         New Hampshire           NH
1445           NJ  total  2010    8802707.0            New Jersey           NJ
1530           NM  total  2010    2064982.0            New Mexico           NM
1541           NY  total  2010   19398228.0              New York           NY
1626           NC  total  2010    9559533.0        North Carolina           NC
1637           ND  total  2010     674344.0          North Dakota           ND
1722           OH  total  2010   11545435.0                  Ohio           OH
1733           OK  total  2010    3759263.0              Oklahoma           OK
1818           OR  total  2010    3837208.0                Oregon           OR
1829           PA  total  2010   12710472.0          Pennsylvania           PA
1914           RI  total  2010    1052669.0          Rhode Island           RI
1925           SC  total  2010    4636361.0        South Carolina           SC
2010           SD  total  2010     816211.0          South Dakota           SD
2021           TN  total  2010    6356683.0             Tennessee           TN
2106           TX  total  2010   25245178.0                 Texas           TX
2117           UT  total  2010    2774424.0                  Utah           UT
2202           VT  total  2010     625793.0               Vermont           VT
2213           VA  total  2010    8024417.0              Virginia           VA
2298           WA  total  2010    6742256.0            Washington           WA
2309           WV  total  2010    1854146.0         West Virginia           WV
2394           WI  total  2010    5689060.0             Wisconsin           WI
2405           WY  total  2010     564222.0               Wyoming           WY
2490           PR  total  2010    3721208.0                   NaN          NaN
2539          USA  total  2010  309326295.0                   NaN          NaN

In [9]:
#面積データと州のフルネームをキーにして結合
df_merged = pd.merge(df_2010_total, df_areas, on="state", how="left")
df_merged

,state/region,ages,year,population,state,abbreviation,area (sq. mi)
0,AL,total,2010,4785570.0,Alabama,AL,52423.0
1,AK,total,2010,713868.0,Alaska,AK,656425.0
2,AZ,total,2010,6408790.0,Arizona,AZ,114006.0
3,AR,total,2010,2922280.0,Arkansas,AR,53182.0
4,CA,total,2010,37333601.0,California,CA,163707.0
5,CO,total,2010,5048196.0,Colorado,CO,104100.0
6,CT,total,2010,3579210.0,Connecticut,CT,5544.0
7,DE,total,2010,899711.0,Delaware,DE,1954.0
8,DC,total,2010,605125.0,District of Columbia,DC,68.0
9,FL,total,2010,18846054.0,Florida,FL,65758.0
10,GA,total,2010,9713248.0,Georgia,GA,59441.0
11,HI,total,2010,1363731.0,Hawaii,HI,10932.0
12,ID,total,2010,1570718.0,Idaho,ID,83574.0
13,IL,total,2010,12839695.0,Illinois,IL,57918.0
14,IN,total,2010,6489965.0,Indiana,IN,36420.0
15,IA,total,2010,3050314.0,Iowa,IA,56276.0
16,KS,total,2010,2858910.0,Kansas,KS,82282.0
17,KY,total,2010,4347698.0,Kentucky,KY,40411.0
18,LA,total,2010,4545392.0,Louisiana,LA,51843.0
19,ME,total,2010,1327366.0,Maine,ME,35387.0
20,MD,total,2010,5787193.0,Maryland,MD,12407.0
21,MA,total,2010,6563263.0,Massachusetts,MA,10555.0
22,MI,total,2010,9876149.0,Michigan,MI,96810.0
23,MN,total,2010,5310337.0,Minnesota,MN,86943.0
24,MS,total,2010,2970047.0,Mississippi,MS,48434.0
25,MO,total,2010,5996063.0,Missouri,MO,69709.0
26,MT,total,2010,990527.0,Montana,MT,147046.0
27,NE,total,2010,1829838.0,Nebraska,NE,77358.0
28,NV,total,2010,2703230.0,Nevada,NV,110567.0
29,NH,total,2010,1316614.0,New Hampshire,NH,9351.0
30,NJ,total,2010,8802707.0,New Jersey,NJ,8722.0
31,NM,total,2010,2064982.0,New Mexico,NM,121593.0
32,NY,total,2010,19398228.0,New York,NY,54475.0
33,NC,total,2010,9559533.0,North Carolina,NC,53821.0
34,ND,total,2010,674344.0,North Dakota,ND,70704.0
35,OH,total,2010,11545435.0,Ohio,OH,44828.0
36,OK,total,2010,3759263.0,Oklahoma,OK,69903.0
37,OR,total,2010,3837208.0,Oregon,OR,98386.0
38,PA,total,2010,12710472.0,Pennsylvania,PA,46058.0
39,RI,total,2010,1052669.0,Rhode Island,RI,1545.0
40,SC,total,2010,4636361.0,South Carolina,SC,32007.0
41,SD,total,2010,816211.0,South Dakota,SD,77121.0
42,TN,total,2010,6356683.0,Tennessee,TN,42146.0
43,TX,total,2010,25245178.0,Texas,TX,268601.0
44,UT,total,2010,2774424.0,Utah,UT,84904.0
45,VT,total,2010,625793.0,Vermont,VT,9615.0
46,VA,total,2010,8024417.0,Virginia,VA,42769.0
47,WA,total,2010,6742256.0,Washington,WA,71303.0
48,WV,total,2010,1854146.0,West Virginia,WV,24231.0
49,WI,total,2010,5689060.0,Wisconsin,WI,65503.0
50,WY,total,2010,564222.0,Wyoming,WY,97818.0
51,PR,total,2010,3721208.0,NaN,NaN,NaN
52,USA,total,2010,309326295.0,NaN,NaN,NaN

In [11]:
# state名,面積がNaNの行を除外
df_clean = df_merged.dropna(subset=["state", "area (sq. mi)"])
df_clean

,state/region,ages,year,population,state,abbreviation,area (sq. mi)
0,AL,total,2010,4785570.0,Alabama,AL,52423.0
1,AK,total,2010,713868.0,Alaska,AK,656425.0
2,AZ,total,2010,6408790.0,Arizona,AZ,114006.0
3,AR,total,2010,2922280.0,Arkansas,AR,53182.0
4,CA,total,2010,37333601.0,California,CA,163707.0
5,CO,total,2010,5048196.0,Colorado,CO,104100.0
6,CT,total,2010,3579210.0,Connecticut,CT,5544.0
7,DE,total,2010,899711.0,Delaware,DE,1954.0
8,DC,total,2010,605125.0,District of Columbia,DC,68.0
9,FL,total,2010,18846054.0,Florida,FL,65758.0
10,GA,total,2010,9713248.0,Georgia,GA,59441.0
11,HI,total,2010,1363731.0,Hawaii,HI,10932.0
12,ID,total,2010,1570718.0,Idaho,ID,83574.0
13,IL,total,2010,12839695.0,Illinois,IL,57918.0
14,IN,total,2010,6489965.0,Indiana,IN,36420.0
15,IA,total,2010,3050314.0,Iowa,IA,56276.0
16,KS,total,2010,2858910.0,Kansas,KS,82282.0
17,KY,total,2010,4347698.0,Kentucky,KY,40411.0
18,LA,total,2010,4545392.0,Louisiana,LA,51843.0
19,ME,total,2010,1327366.0,Maine,ME,35387.0
20,MD,total,2010,5787193.0,Maryland,MD,12407.0
21,MA,total,2010,6563263.0,Massachusetts,MA,10555.0
22,MI,total,2010,9876149.0,Michigan,MI,96810.0
23,MN,total,2010,5310337.0,Minnesota,MN,86943.0
24,MS,total,2010,2970047.0,Mississippi,MS,48434.0
25,MO,total,2010,5996063.0,Missouri,MO,69709.0
26,MT,total,2010,990527.0,Montana,MT,147046.0
27,NE,total,2010,1829838.0,Nebraska,NE,77358.0
28,NV,total,2010,2703230.0,Nevada,NV,110567.0
29,NH,total,2010,1316614.0,New Hampshire,NH,9351.0
30,NJ,total,2010,8802707.0,New Jersey,NJ,8722.0
31,NM,total,2010,2064982.0,New Mexico,NM,121593.0
32,NY,total,2010,19398228.0,New York,NY,54475.0
33,NC,total,2010,9559533.0,North Carolina,NC,53821.0
34,ND,total,2010,674344.0,North Dakota,ND,70704.0
35,OH,total,2010,11545435.0,Ohio,OH,44828.0
36,OK,total,2010,3759263.0,Oklahoma,OK,69903.0
37,OR,total,2010,3837208.0,Oregon,OR,98386.0
38,PA,total,2010,12710472.0,Pennsylvania,PA,46058.0
39,RI,total,2010,1052669.0,Rhode Island,RI,1545.0
40,SC,total,2010,4636361.0,South Carolina,SC,32007.0
41,SD,total,2010,816211.0,South Dakota,SD,77121.0
42,TN,total,2010,6356683.0,Tennessee,TN,42146.0
43,TX,total,2010,25245178.0,Texas,TX,268601.0
44,UT,total,2010,2774424.0,Utah,UT,84904.0
45,VT,total,2010,625793.0,Vermont,VT,9615.0
46,VA,total,2010,8024417.0,Virginia,VA,42769.0
47,WA,total,2010,6742256.0,Washington,WA,71303.0
48,WV,total,2010,1854146.0,West Virginia,WV,24231.0
49,WI,total,2010,5689060.0,Wisconsin,WI,65503.0
50,WY,total,2010,564222.0,Wyoming,WY,97818.0

In [12]:
# 人口密度を計算
df_clean["density"] = df_clean["population"] / df_clean["area (sq. mi)"]
df_clean

,state/region,ages,year,population,state,abbreviation,area (sq. mi),density
0,AL,total,2010,4785570.0,Alabama,AL,52423.0,91.287603
1,AK,total,2010,713868.0,Alaska,AK,656425.0,1.087509
2,AZ,total,2010,6408790.0,Arizona,AZ,114006.0,56.214497
3,AR,total,2010,2922280.0,Arkansas,AR,53182.0,54.948667
4,CA,total,2010,37333601.0,California,CA,163707.0,228.051342
5,CO,total,2010,5048196.0,Colorado,CO,104100.0,48.493718
6,CT,total,2010,3579210.0,Connecticut,CT,5544.0,645.600649
7,DE,total,2010,899711.0,Delaware,DE,1954.0,460.445752
8,DC,total,2010,605125.0,District of Columbia,DC,68.0,8898.897059
9,FL,total,2010,18846054.0,Florida,FL,65758.0,286.597129
10,GA,total,2010,9713248.0,Georgia,GA,59441.0,163.409902
11,HI,total,2010,1363731.0,Hawaii,HI,10932.0,124.746707
12,ID,total,2010,1570718.0,Idaho,ID,83574.0,18.794338
13,IL,total,2010,12839695.0,Illinois,IL,57918.0,221.687472
14,IN,total,2010,6489965.0,Indiana,IN,36420.0,178.197831
15,IA,total,2010,3050314.0,Iowa,IA,56276.0,54.202751
16,KS,total,2010,2858910.0,Kansas,KS,82282.0,34.745266
17,KY,total,2010,4347698.0,Kentucky,KY,40411.0,107.586994
18,LA,total,2010,4545392.0,Louisiana,LA,51843.0,87.676099
19,ME,total,2010,1327366.0,Maine,ME,35387.0,37.509990
20,MD,total,2010,5787193.0,Maryland,MD,12407.0,466.445797
21,MA,total,2010,6563263.0,Massachusetts,MA,10555.0,621.815538
22,MI,total,2010,9876149.0,Michigan,MI,96810.0,102.015794
23,MN,total,2010,5310337.0,Minnesota,MN,86943.0,61.078373
24,MS,total,2010,2970047.0,Mississippi,MS,48434.0,61.321530
25,MO,total,2010,5996063.0,Missouri,MO,69709.0,86.015622
26,MT,total,2010,990527.0,Montana,MT,147046.0,6.736171
27,NE,total,2010,1829838.0,Nebraska,NE,77358.0,23.654153
28,NV,total,2010,2703230.0,Nevada,NV,110567.0,24.448796
29,NH,total,2010,1316614.0,New Hampshire,NH,9351.0,140.799273
30,NJ,total,2010,8802707.0,New Jersey,NJ,8722.0,1009.253268
31,NM,total,2010,2064982.0,New Mexico,NM,121593.0,16.982737
32,NY,total,2010,19398228.0,New York,NY,54475.0,356.094135
33,NC,total,2010,9559533.0,North Carolina,NC,53821.0,177.617157
34,ND,total,2010,674344.0,North Dakota,ND,70704.0,9.537565
35,OH,total,2010,11545435.0,Ohio,OH,44828.0,257.549634
36,OK,total,2010,3759263.0,Oklahoma,OK,69903.0,53.778278
37,OR,total,2010,3837208.0,Oregon,OR,98386.0,39.001565
38,PA,total,2010,12710472.0,Pennsylvania,PA,46058.0,275.966651
39,RI,total,2010,1052669.0,Rhode Island,RI,1545.0,681.339159
40,SC,total,2010,4636361.0,South Carolina,SC,32007.0,144.854594
41,SD,total,2010,816211.0,South Dakota,SD,77121.0,10.583512
42,TN,total,2010,6356683.0,Tennessee,TN,42146.0,150.825298
43,TX,total,2010,25245178.0,Texas,TX,268601.0,93.987655
44,UT,total,2010,2774424.0,Utah,UT,84904.0,32.677188
45,VT,total,2010,625793.0,Vermont,VT,9615.0,65.085075
46,VA,total,2010,8024417.0,Virginia,VA,42769.0,187.622273
47,WA,total,2010,6742256.0,Washington,WA,71303.0,94.557817
48,WV,total,2010,1854146.0,West Virginia,WV,24231.0,76.519582
49,WI,total,2010,5689060.0,Wisconsin,WI,65503.0,86.851900
50,WY,total,2010,564222.0,Wyoming,WY,97818.0,5.768079

## 課題3

```state/region```、```ages```と```years```でデータフレームをグループして、各グループで$\frac{population}{area (sq. mi)}$の形で人口密度を計算してください。

In [ ]:
#全人口データに面積データを結合
df_full = pd.merge(df_pop2, df_areas, on="state", how="left")

In [14]:
#プエルトリコとUSJの行を消す
df_full = df_full.dropna(subset=["state", "area (sq. mi)"])
df_full

,state/region,ages,year,population,state,abbreviation,area (sq. mi)
0,AL,under18,2012,1117489.0,Alabama,AL,52423.0
1,AL,total,2012,4817528.0,Alabama,AL,52423.0
2,AL,under18,2010,1130966.0,Alabama,AL,52423.0
3,AL,total,2010,4785570.0,Alabama,AL,52423.0
4,AL,under18,2011,1125763.0,Alabama,AL,52423.0
...,...,...,...,...,...,...,...
2443,WY,under18,1993,137458.0,Wyoming,WY,97818.0
2444,WY,total,1991,459260.0,Wyoming,WY,97818.0
2445,WY,under18,1991,136720.0,Wyoming,WY,97818.0
2446,WY,under18,1990,136078.0,Wyoming,WY,97818.0
2447,WY,total,1990,453690.0,Wyoming,WY,97818.0

In [16]:
#state/region, ages, year でグループ化し、各グループで人口密度を計算
def add_density(group):
    group["density"] = group["population"] / group["area (sq. mi)"]
    return group

df_density = df_full.groupby(["state/region", "ages", "year"]).apply(add_density)
df_density

                                population    state abbreviation  \
state/region ages    year
AK           total   1990 48      553290.0   Alaska           AK
                     1991 55      570193.0   Alaska           AK
                     1992 50      588736.0   Alaska           AK
                     1993 56      599434.0   Alaska           AK
                     1994 53      603308.0   Alaska           AK
...                                    ...      ...          ...
WY           under18 2009 2407    134960.0  Wyoming           WY
                     2010 2404    135351.0  Wyoming           WY
                     2011 2403    135407.0  Wyoming           WY
                     2012 2401    136526.0  Wyoming           WY
                     2013 2409    137679.0  Wyoming           WY

                                area (sq. mi)   density
state/region ages    year
AK           total   1990 48         656425.0  0.842884
                     1991 55         656425.0  0.868634
                     1992 50         656425.0  0.896882
                     1993 56         656425.0  0.913180
                     1994 53         656425.0  0.919081
...                                       ...       ...
WY           under18 2009 2407        97818.0  1.379705
                     2010 2404        97818.0  1.383702
                     2011 2403        97818.0  1.384275
                     2012 2401        97818.0  1.395714
                     2013 2409        97818.0  1.407502

[2448 rows x 5 columns]